parameters:
    darvin_payment.admin.form.renderer.operation.class: Darvin\PaymentBundle\Form\Renderer\Admin\OperationFormRenderer

    darvin_payment.admin.view.widget.payment_event_level.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentEventLevelWidget

    darvin_payment.admin.view.widget.payment_operation.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentOperationWidget

    darvin_payment.admin.view.widget.payment_state.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentStateWidget

services:
    Darvin\PaymentBundle\Form\Renderer\Admin\OperationFormRendererInterface: '@darvin_payment.admin.form.renderer.operation'

    darvin_payment.admin.form.renderer.operation:
        class: '%darvin_payment.admin.form.renderer.operation.class%'
        arguments:
            - '@twig'
            - '@darvin_payment.url.builder'
            - '@state_machine.payment'

    darvin_payment.admin.view.widget.payment_event_level:
        class:  '%darvin_payment.admin.view.widget.payment_event_level.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.admin.view.widget.payment_operation:
        class:  '%darvin_payment.admin.view.widget.payment_operation.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@darvin_payment.admin.form.renderer.operation'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.admin.view.widget.payment_state:
        class:  '%darvin_payment.admin.view.widget.payment_state.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }
