parameters:
    darvin_payment.admin.refund.controller.class: Darvin\PaymentBundle\Controller\Admin\RefundController

services:
    darvin_payment.admin.refund.controller:
        class:  '%darvin_payment.admin.refund.controller.class%'
        parent: darvin_payment.controller.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setFormRenderer,         [ '@darvin_payment.admin.form.renderer.operation' ] ]
        tags:
            - { name: controller.service_arguments }
