parameters:
    darvin_payment.bridge.sberbank.class: Darvin\PaymentBundle\Bridge\SberbankBridge

services:
    darvin_payment.bridge.sberbank:
        class: '%darvin_payment.bridge.sberbank.class%'
        arguments:
            - '@darvin_payment.receipt.factory_registry'
            - '@darvin_payment.url.builder'
            - '@darvin_payment.logger'
            - '@translator'
        calls:
            - [ setGatewayConfig, [ '%darvin_payment.bridges.sberbank.parameters%' ] ]
            - [ setReceiptConfig, [ '%darvin_payment.bridges.sberbank.receipt%' ] ]
