parameters:
    darvin_payment.bridge.yookassa.class: Darvin\PaymentBundle\Bridge\YookassaBridge

services:
    darvin_payment.bridge.yookassa:
        class: '%darvin_payment.bridge.yookassa.class%'
        arguments:
            - '@darvin_payment.url.builder'
            - '@darvin_payment.logger'
            - '@darvin_payment.receipt.factory_registry'
            - '@translator'
        calls:
            - [ setGatewayConfig, [ '%darvin_payment.bridges.yookassa.parameters.gateway%' ] ]
            - [ setReceiptConfig, [ '%darvin_payment.bridges.yookassa.parameters.receipt%' ] ]
