services:
#    darvin_payment.example:
#        class: Darvin\PaymentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    Darvin\PaymentBundle\PaymentManager\DefaultPaymentManager:
        arguments: ['@doctrine.orm.entity_manager','@Darvin\PaymentBundle\Token\Manager\TokenManagerInterface']
        public: false

    Darvin\PaymentBundle\PaymentManager\PaymentManagerInterface:
        alias: Darvin\PaymentBundle\PaymentManager\DefaultPaymentManager
        public: true

    Darvin\PaymentBundle\Gateway\Factory\DefaultGatewayFactory:
        arguments: ['@request_stack']
        public: false

    Darvin\PaymentBundle\Gateway\Factory\GatewayFactoryInterface:
        alias: Darvin\PaymentBundle\Gateway\Factory\DefaultGatewayFactory
        public: true

    Darvin\PaymentBundle\UrlBuilder\DefaultPaymentUrlBuilder:
        arguments: ['@router']
        public: false

    Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilderInterface:
        alias: Darvin\PaymentBundle\UrlBuilder\DefaultPaymentUrlBuilder

    Darvin\PaymentBundle\Token\Manager\DefaultTokenManager:
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    Darvin\PaymentBundle\Token\Manager\TokenManagerInterface:
        alias: Darvin\PaymentBundle\Token\Manager\DefaultTokenManager

    Darvin\PaymentBundle\Gateway\ParametersBridge\TelrGatewayParametersBridge:
        arguments: ['@Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilderInterface']
        tags:
            - { name: darvin_payment.parameters_bridge, gateway: telr }