services:
#    darvin_payment.example:
#        class: Darvin\PaymentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    Darvin\PaymentBundle\Controller\PaymentController:
        arguments:
            - '@Darvin\PaymentBundle\Gateway\Factory\GatewayFactoryInterface'
            - '@Darvin\PaymentBundle\PaymentManager\PaymentManagerInterface'
            - '@Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilderInterface'
            - '@Darvin\PaymentBundle\Token\Manager\PaymentTokenManagerInterface'
        tags:
            - { name: controller.service_arguments }


    Darvin\PaymentBundle\PaymentManager\DefaultPaymentManager:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Darvin\Utils\ORM\EntityResolverInterface'
            - '@Darvin\PaymentBundle\Token\Manager\PaymentTokenManager'
#            - '%darvin_payment.default_currency%'
        public: true

    Darvin\PaymentBundle\PaymentManager\PaymentManagerInterface:
        alias: Darvin\PaymentBundle\PaymentManager\DefaultPaymentManager
        public: true

    Darvin\PaymentBundle\Gateway\Factory\DefaultGatewayFactory:
        arguments:
            - '@request_stack'
        public: true

    Darvin\PaymentBundle\Gateway\Factory\GatewayFactoryInterface:
        alias: Darvin\PaymentBundle\Gateway\Factory\DefaultGatewayFactory
        public: true

    Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilder:
        arguments:
            - '@router'
        public: true

    Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilderInterface:
        alias: Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilder

    Darvin\PaymentBundle\Token\Manager\PaymentTokenManager:
        arguments:
            - '@doctrine.orm.entity_manager'
        public: true

    Darvin\PaymentBundle\Token\Manager\PaymentTokenManagerInterface:
        alias: Darvin\PaymentBundle\Token\Manager\PaymentTokenManager

    Darvin\PaymentBundle\Gateway\ParametersBridge\TelrGatewayParametersBridge:
        arguments:
            - '@Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilderInterface'
        tags:
            - { name: darvin_payment.parameters_bridge, gateway: telr }
