parameters:
    darvin_payment.admin.controller.approve.class: Darvin\PaymentBundle\Controller\Admin\ApproveController
    darvin_payment.admin.controller.capture.class: Darvin\PaymentBundle\Controller\Admin\CaptureController
    darvin_payment.admin.view.widget.payment_state.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentStateWidget
    darvin_payment.admin.view.widget.payment_operation.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentOperationWidget
    darvin_payment.admin.from.renderer.approve.class: Darvin\PaymentBundle\Form\Renderer\ApproveFormRenderer
    darvin_payment.admin.form.renderer.capture.class: Darvin\PaymentBundle\Form\Renderer\CaptureFormRenderer

services:
    darvin_payment.admin.controller.approve:
        class: '%darvin_payment.admin.controller.approve.class%'
        parent: darvin_payment.controller.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
        tags:
            - { name: controller.service_arguments }

    darvin_payment.admin.controller.capture:
        class: '%darvin_payment.admin.controller.capture.class%'
        parent: darvin_payment.controller.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
            - [ setCaptureFormRenderer,  [ '@darvin_payment.admin.form.renderer.capture' ] ]
        tags:
            - { name: controller.service_arguments }

    darvin_payment.admin.view.widget.payment_state:
        class:  '%darvin_payment.admin.view.widget.payment_state.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.admin.view.widget.payment_operation:
        class:  '%darvin_payment.admin.view.widget.payment_operation.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - "@darvin_payment.admin.from.renderer.approve"
            - "@darvin_payment.admin.form.renderer.capture"
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.admin.from.renderer.approve:
        class:  '%darvin_payment.admin.from.renderer.approve.class%'
        arguments:
            - '@darvin_payment.url.builder'
            - '@twig'

    darvin_payment.admin.form.renderer.capture:
        class:  '%darvin_payment.admin.form.renderer.capture.class%'
        arguments:
            - '@darvin_payment.url.builder'
            - '@twig'
