parameters:
    darvin_payment.controller.admin.approve.class: Darvin\PaymentBundle\Controller\Admin\ApproveController
    darvin_payment.controller.admin.capture.class: Darvin\PaymentBundle\Controller\Admin\CaptureController
    darvin_payment.admin.view.widget.payment_state.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentStateWidget
    darvin_payment.admin.view.widget.payment_operation.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentOperationWidget
    darvin_payment.renderer.approve_form_renderer.class: Darvin\PaymentBundle\Form\Renderer\ApproveFormRenderer
    darvin_payment.renderer.capture_form_renderer.class: Darvin\PaymentBundle\Form\Renderer\CaptureFormRenderer

services:
    darvin_payment.controller.admin.approve:
        class: '%darvin_payment.controller.admin.approve.class%'
        parent: darvin_payment.controller.payment.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
        public: true

    darvin_payment.controller.admin.capture:
        class: '%darvin_payment.controller.admin.capture.class%'
        parent: darvin_payment.controller.payment.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
            - [ setCaptureFormRenderer,  [ '@darvin_payment.renderer.capture_form_renderer' ] ]
        public: true

    darvin_payment.admin.view.widget.payment_state:
        class:  '%darvin_payment.admin.view.widget.payment_state.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.admin.view.widget.payment_operation:
        class:  '%darvin_payment.admin.view.widget.payment_operation.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - "@darvin_payment.renderer.approve_form_renderer"
            - "@darvin_payment.renderer.capture_form_renderer"
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.renderer.approve_form_renderer:
        class:  '%darvin_payment.renderer.approve_form_renderer.class%'
        arguments:
            - '@darvin_payment.url.payment_url_builder'
            - '@twig'

    darvin_payment.renderer.capture_form_renderer:
        class:  '%darvin_payment.renderer.capture_form_renderer.class%'
        arguments:
            - '@darvin_payment.url.payment_url_builder'
            - '@twig'
