parameters:
    darvin_payment.admin.form.renderer.abstract.class: Darvin\PaymentBundle\Form\Renderer\AbstractFormRenderer
    darvin_payment.admin.view.widget.event_level.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentEventLevelWidget
    darvin_payment.admin.view.widget.payment_operation.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentOperationWidget
    darvin_payment.admin.view.widget.payment_state.class: Darvin\PaymentBundle\Admin\View\Widget\PaymentStateWidget

services:
    darvin_payment.admin.form.renderer.abstract:
        class: '%darvin_payment.admin.form.renderer.abstract.class%'
        abstract: true
        arguments:
            - '@darvin_payment.url.builder'
            - '@twig'
            - '@state_machine.payment'

    darvin_payment.admin.view.widget.event_level:
        class:  '%darvin_payment.admin.view.widget.event_level.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.admin.view.widget.payment_operation:
        class:  '%darvin_payment.admin.view.widget.payment_operation.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@state_machine.payment'
        calls:
            - [ setApproveFormRenderer, [ '@?darvin_payment.admin.form.renderer.approve' ] ]
            - [ setCaptureFormRenderer, [ '@?darvin_payment.admin.form.renderer.capture' ] ]
            - [ setRefundFormRenderer,  [ '@?darvin_payment.admin.form.renderer.refund' ] ]
            - [ setVoidFormRenderer,    [ '@?darvin_payment.admin.form.renderer.void' ] ]
        tags:
            - { name: darvin_admin.view_widget }

    darvin_payment.admin.view.widget.payment_state:
        class:  '%darvin_payment.admin.view.widget.payment_state.class%'
        parent: darvin_admin.view.widget.abstract
        arguments:
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }
