parameters:
    darvin_payment.admin.controller.approve.class: Darvin\PaymentBundle\Controller\Admin\ApproveController
    darvin_payment.admin.form.renderer.approve.class: Darvin\PaymentBundle\Form\Renderer\ApproveFormRenderer

services:
    darvin_payment.admin.controller.approve:
        class: '%darvin_payment.admin.controller.approve.class%'
        parent: darvin_payment.controller.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
        tags:
            - { name: controller.service_arguments }

    darvin_payment.admin.form.renderer.approve:
        class: '%darvin_payment.admin.form.renderer.approve.class%'
        parent: darvin_payment.admin.form.renderer.abstract
