parameters:
    darvin_payment.configuration.class: Darvin\PaymentBundle\Config\PaymentConfig

    darvin_payment.configuration.notification_emails_form_type.class: Darvin\PaymentBundle\Form\Type\Config\NotificationEmailsType

services:
    darvin_payment.configuration:
        class: '%darvin_payment.configuration.class%'
        arguments:
            - '@darvin_payment.mailer.status_provider'
            - '%darvin_payment.mailer.enabled%'
        tags:
            - { name: darvin_config.configuration }

    darvin_payment.configuration.notification_emails_form_type:
        class: '%darvin_payment.configuration.notification_emails_form_type.class%'
        arguments:
            - '@darvin_payment.mailer.status_provider'
        tags:
            - { name: form.type }
