parameters:
    darvin_payment.controller.authorize.class: Darvin\PaymentBundle\Controller\AuthorizationController
    darvin_payment.controller.canceled.class: Darvin\PaymentBundle\Controller\CanceledController
    darvin_payment.controller.failed.class: Darvin\PaymentBundle\Controller\FailedController
    darvin_payment.controller.purchase.class: Darvin\PaymentBundle\Controller\PurchaseController
    darvin_payment.controller.success.class: Darvin\PaymentBundle\Controller\SuccessController

services:
    darvin_payment.controller.autorize:
        class: '%darvin_payment.controller.authorize.class%'
        arguments:
            - '@darvin_payment.gateway.gateway_factory'
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@darvin_payment.state.manager'
            - '@darvin_payment.url_builder.payment_url_builder'
            - '@twig'

    darvin_payment.controller.canceled:
        class: '%darvin_payment.controller.canceled.class%'
        arguments:
            - '@darvin_payment.gateway.gateway_factory'
            - '@doctrine.orm.entity_manager'
            - '@darvin_payment.state.manager'
            - '@twig'

    darvin_payment.controller.failed:
        class: '%darvin_payment.controller.failed.class%'
        arguments:
            - '@darvin_payment.gateway.gateway_factory'
            - '@doctrine.orm.entity_manager'
            - '@darvin_payment.state.manager'
            - '@twig'

    darvin_payment.controller.purchase:
        class: '%darvin_payment.controller.purchase.class%'
        arguments:
            - '@darvin_payment.gateway.gateway_factory'
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@darvin_payment.state.manager'
            - '@darvin_payment.url_builder.payment_url_builder'
            - '@twig'

    darvin_payment.controller.success:
        class: '%darvin_payment.controller.success.class%'
        arguments:
            - '@darvin_payment.gateway.gateway_factory'
            - '@doctrine.orm.entity_manager'
            - '@darvin_payment.state.manager'
            - '@darvin_payment.url_builder.payment_url_builder'
            - '@twig'
