parameters:
    darvin_payment.controller.payment.abstract.class: Darvin\PaymentBundle\Controller\AbstractController
    darvin_payment.controller.payment.authorize.class: Darvin\PaymentBundle\Controller\Payment\AuthorizeController
    darvin_payment.controller.payment.cancel.class: Darvin\PaymentBundle\Controller\Payment\CancelController
    darvin_payment.controller.payment.complete_authorize.class: Darvin\PaymentBundle\Controller\Payment\CompleteAuthorizeController
    darvin_payment.controller.payment.complete_purchase.class: Darvin\PaymentBundle\Controller\Payment\CompletePurchaseController
    darvin_payment.controller.payment.fail.class: Darvin\PaymentBundle\Controller\Payment\FailController
    darvin_payment.controller.payment.purchase.class: Darvin\PaymentBundle\Controller\Payment\PurchaseController
    darvin_payment.controller.payment.success.class: Darvin\PaymentBundle\Controller\Payment\SuccessController

services:
    darvin_payment.controller.payment.abstract:
        abstract:  true
        class: '%darvin_payment.controller.payment.abstract.class%'
        calls:
            - [ setGatewayFactory, ['@darvin_payment.gateway.gateway_factory'] ]
            - [ setEntityManager,  ['@doctrine.orm.entity_manager'] ]
            - [ setTwig,           ['@twig'] ]
            - [ setLogger,         ['@?monolog.logger.payment'] ]
            - [ setUrlBuilder,     ['@darvin_payment.url.payment_url_builder'] ]
            - [ setWorkflow,       ['@state_machine.payment'] ]

    darvin_payment.controller.payment.autorize:
        class: '%darvin_payment.controller.payment.authorize.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        arguments:
            - '@form.factory'
        public: true

    darvin_payment.controller.payment.complete_authorize:
        class: '%darvin_payment.controller.payment.complete_authorize.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        public: true

    darvin_payment.controller.payment.complete_purchase:
        class: '%darvin_payment.controller.payment.complete_purchase.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        public: true

    darvin_payment.controller.payment.cancel:
        class: '%darvin_payment.controller.payment.cancel.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        public: true

    darvin_payment.controller.payment.fail:
        class: '%darvin_payment.controller.payment.fail.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        public: true

    darvin_payment.controller.payment.purchase:
        class: '%darvin_payment.controller.payment.purchase.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        arguments:
            - '@form.factory'
        public: true
