parameters:
    darvin_payment.controller.payment.abstract.class: Darvin\PaymentBundle\Controller\AbstractController
    darvin_payment.controller.payment.authorize.class: Darvin\PaymentBundle\Controller\Payment\AuthorizeController
    darvin_payment.controller.payment.authorize_success.class: Darvin\PaymentBundle\Controller\Payment\AuthorizeSuccessController
    darvin_payment.controller.payment.canceled.class: Darvin\PaymentBundle\Controller\Payment\CanceledController
    darvin_payment.controller.payment.failed.class: Darvin\PaymentBundle\Controller\Payment\FailedController
    darvin_payment.controller.payment.purchase.class: Darvin\PaymentBundle\Controller\Payment\PurchaseController
    darvin_payment.controller.payment.purchase_success.class: Darvin\PaymentBundle\Controller\Payment\PurchaseSuccessController

services:
    darvin_payment.controller.payment.abstract:
        class: '%darvin_payment.controller.payment.abstract.class%'
        arguments:
            - '@darvin_payment.gateway.gateway_factory'
            - '@doctrine.orm.entity_manager'
            - '@twig'
            - '@darvin_payment.url.payment_url_builder'
            - '@workflow.payment'
        calls:
            - [ setLogger, ['@?monolog.logger.payment'] ]

    darvin_payment.controller.payment.autorize:
        class: '%darvin_payment.controller.payment.authorize.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        arguments:
            - '@form.factory'

    darvin_payment.controller.payment.authorize_success:
        class: '%darvin_payment.controller.payment.authorize_success.class%'
        parent: 'darvin_payment.controller.payment.abstract'

    darvin_payment.controller.payment.canceled:
        class: '%darvin_payment.controller.payment.canceled.class%'
        parent: 'darvin_payment.controller.payment.abstract'

    darvin_payment.controller.payment.failed:
        class: '%darvin_payment.controller.payment.failed.class%'
        parent: 'darvin_payment.controller.payment.abstract'

    darvin_payment.controller.payment.purchase:
        class: '%darvin_payment.controller.payment.purchase.class%'
        parent: 'darvin_payment.controller.payment.abstract'
        arguments:
            - '@form.factory'

    darvin_payment.controller.payment.purchase_success:
        class: '%darvin_payment.controller.payment.purchase_success.class%'
        parent: 'darvin_payment.controller.payment.abstract'
