services:
    Darvin\PaymentBundle\Controller\PaymentController:
        arguments:
            - '@darvin_payment.gateway.gateway_factory'
            - '@darvin_payment.payment.manager'
            - '@darvin_payment.state.manager'
            - '@darvin_payment.url_builder.payment_url_builder'
            - '@darvin_payment.token.payment_token_manager'
        tags:
            - { name: controller.service_arguments }
