parameters:
    darvin_payment.gateway.gateway_factory.class: Darvin\PaymentBundle\Gateway\Factory\GatewayFactory

services:
    darvin_payment.gateway.gateway_factory:
        class: '%darvin_payment.gateway.gateway_factory.class%'
        arguments:
            - '@request_stack'
