parameters:
    darvin_payment.gateway.factory.class: Darvin\PaymentBundle\Gateway\Factory\GatewayFactory

services:
    darvin_payment.gateway.factory:
        class: '%darvin_payment.gateway.factory.class%'
        arguments:
            - '@request_stack'
