parameters:
    darvin_payment.mailer.factory.class: Darvin\PaymentBundle\Mailer\Factory\EmailFactory

    darvin_payment.mailer.subscriber.payment_events.class: Darvin\PaymentBundle\EventListener\PaymentEventsSubscriber

services:
    darvin_payment.mailer.factory:
        class: '%darvin_payment.mailer.factory.class%'
        arguments:
            - '@darvin_mailer.factory.template'
            - '@darvin_payment.configuration'
            - '@translator'

    darvin_payment.mailer.subscriber.payment_events:
        class: '%darvin_payment.mailer.subscriber.payment_events.class%'
        arguments:
            - '@darvin_payment.mailer.factory'
            - '@darvin_mailer.mailer'
            - '@darvin_payment.status.provider'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [ setLogger, [ '@?logger' ] ]
