parameters:
    darvin_payment.mailer.factory.class: Darvin\PaymentBundle\Mailer\Factory\EmailFactory

services:
    darvin_payment.mailer.factory:
        class: '%darvin_payment.mailer.factory.class%'
        arguments:
            - '@darvin_mailer.factory.template'
            - '@darvin_payment.configuration'
            - '@translator'
