parameters:
    darvin_payment.mailer.event_subscriber.email_state_change.class: Darvin\PaymentBundle\EventListener\Mailer\EmailStateChangeSubscriber

    darvin_payment.mailer.factory.class: Darvin\PaymentBundle\Mailer\Factory\PaymentEmailFactory

services:
    darvin_payment.mailer.event_subscriber.email_state_change:
        class: '%darvin_payment.mailer.event_subscriber.email_state_change.class%'
        arguments:
            - '@darvin_payment.mailer.factory'
            - '@darvin_payment.logger'
            - '@darvin_mailer.mailer'
            - '@darvin_payment.state.provider'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    darvin_payment.mailer.factory:
        class: '%darvin_payment.mailer.factory.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_mailer.factory.template'
            - '@darvin_payment.config'
            - '@translator'
