parameters:
    darvin_payment.mailer.factory.class: Darvin\PaymentBundle\Mailer\Factory\AbstractEmailFactory

    darvin_payment.mailer.subscriber.payment_events.class: Darvin\PaymentBundle\EventListener\PaymentEventsSubscriber

    darvin_payment.mailer.status_provider.class: Darvin\PaymentBundle\Mailer\Provider\StatusProvider

services:
    darvin_payment.mailer.factory:
        class: '%darvin_payment.mailer.factory.class%'
        arguments:
            - '@darvin_mailer.factory.template'
            - '@darvin_payment.configuration'
            - '@translator'

    darvin_payment.mailer.subscriber.payment_events:
        class: '%darvin_payment.mailer.subscriber.payment_events.class%'
        arguments:
            - '@darvin_payment.mailer.factory'
            - '@darvin_mailer.mailer'
        tags:
            - { name: kernel.event_subscriber }

    darvin_payment.mailer.status_provider:
        class: '%darvin_payment.mailer.status_provider.class%'
