parameters:
    darvin_payment.payment_manager.class: 'Darvin\PaymentBundle\Manager\PaymentManager'

services:
    Darvin\PaymentBundle\Manager\PaymentManagerInterface: '@darvin_payment.payment_manager'

    darvin_payment.payment_manager:
        class: '%darvin_payment.payment_manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Darvin\Utils\ORM\EntityResolverInterface'
            - '@event_dispatcher'
            - '@darvin_payment.token.payment_token_manager'
            - '%darvin_payment.default_currency%'
        public: true
