parameters:
    darvin_payment.payment.factory.class: Darvin\PaymentBundle\Payment\Factory\PaymentFactory

services:
    Darvin\PaymentBundle\Payment\Factory\PaymentFactoryInterface: '@darvin_payment.payment.factory'

    darvin_payment.payment.factory:
        class: '%darvin_payment.payment.factory.class%'
        arguments:
            - '@darvin_utils.orm.entity_resolver'
            - '@validator'
            - '@state_machine.payment'
            - '%darvin_payment.auto_approval%'
            - '%darvin_payment.default_currency%'
