parameters:
    darvin_payment.payment.factory.class: Darvin\PaymentBundle\Payment\PaymentFactory

services:
    Darvin\PaymentBundle\Payment\PaymentFactoryInterface: '@darvin_payment.payment.factory'

    darvin_payment.payment.factory:
        class: '%darvin_payment.payment.factory.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Darvin\Utils\ORM\EntityResolverInterface'
            - '@workflow.payment'
            - '%darvin_payment.default_currency%'
            - '%darvin_payment.auto_approval%'
        public: true
