parameters:
    darvin_payment.admin.controller.capture.class: Darvin\PaymentBundle\Controller\Admin\CaptureController
    darvin_payment.admin.controller.void.class: Darvin\PaymentBundle\Controller\Admin\VoidController
    darvin_payment.admin.form.renderer.capture.class: Darvin\PaymentBundle\Form\Renderer\CaptureFormRenderer
    darvin_payment.admin.form.renderer.void.class: Darvin\PaymentBundle\Form\Renderer\VoidFormRenderer

services:
    darvin_payment.admin.controller.capture:
        class: '%darvin_payment.admin.controller.capture.class%'
        parent: darvin_payment.controller.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
            - [ setFormRenderer,         [ '@darvin_payment.admin.form.renderer.capture' ] ]
        tags:
            - { name: controller.service_arguments }

    darvin_payment.admin.controller.void:
        class: '%darvin_payment.admin.controller.void.class%'
        parent: darvin_payment.controller.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setRequestStack,         [ '@request_stack' ] ]
            - [ setFormRenderer,         [ '@darvin_payment.admin.form.renderer.void' ] ]
        tags:
            - { name: controller.service_arguments }

    darvin_payment.admin.form.renderer.capture:
        class:  '%darvin_payment.admin.form.renderer.capture.class%'
        parent: darvin_payment.admin.form.renderer.abstract

    darvin_payment.admin.form.renderer.void:
        class: '%darvin_payment.admin.form.renderer.void.class%'
        parent: darvin_payment.admin.form.renderer.abstract
