parameters:
    darvin_payment.receipt.factory_registry.class: Darvin\PaymentBundle\Receipt\ReceiptFactoryRegistry

services:
    darvin_payment.receipt.factory_registry:
        class: '%darvin_payment.receipt.factory_registry.class%'
