parameters:
    darvin_payment.redirect.factory.class: Darvin\PaymentBundle\Redirect\RedirectFactory

services:
    darvin_payment.redirect.factory:
        class: '%darvin_payment.redirect.factory.class%'
        arguments:
            - '@Darvin\Utils\ORM\EntityResolverInterface'
