parameters:
    darvin_payment.admin.controller.refund.class: Darvin\PaymentBundle\Controller\Admin\RefundController
    darvin_payment.admin.form.renderer.refund.class: Darvin\PaymentBundle\Form\Renderer\RefundFormRenderer

services:
    darvin_payment.admin.controller.refund:
        class: '%darvin_payment.admin.controller.refund.class%'
        parent: darvin_payment.controller.abstract
        calls:
            - [ setAdminRouter,          [ '@darvin_admin.router' ] ]
            - [ setAuthorizationChecker, [ '@security.authorization_checker' ] ]
            - [ setFlashNotifier,        [ '@darvin_utils.flash.notifier' ] ]
            - [ setFormRenderer,         [ '@darvin_payment.admin.form.renderer.refund' ] ]
        tags:
            - { name: controller.service_arguments }

    darvin_payment.admin.form.renderer.refund:
        class: '%darvin_payment.admin.form.renderer.refund.class%'
        parent: darvin_payment.admin.form.renderer.abstract
