parameters:
    darvin_payment.state.manager.class:  Darvin\PaymentBundle\State\Manager\StateManager
    darvin_payment.state.provider.class: Darvin\PaymentBundle\State\Provider\StateProvider

services:
    darvin_payment.state.provider:
        class: '%darvin_payment.state.provider.class%'

    darvin_payment.state.manager:
        class: '%darvin_payment.state.manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@darvin_payment.token.payment_token_manager'
