parameters:
    darvin_payment.state.provider.class: Darvin\PaymentBundle\State\Provider\StateProvider

services:
    darvin_payment.state.provider:
        class: '%darvin_payment.state.provider.class%'
