parameters:
    darvin_payment.state.changed.event_subscriber.log.class: Darvin\PaymentBundle\EventListener\State\Changed\LogSubscriber

    darvin_payment.state.provider.class: Darvin\PaymentBundle\State\Provider\StateProvider

services:
    darvin_payment.state.changed.event_subscriber.log:
        class: '%darvin_payment.state.changed.event_subscriber.log.class%'
        arguments:
            - '@darvin_payment.logger'
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    darvin_payment.state.provider:
        class: '%darvin_payment.state.provider.class%'
