parameters:
    darvin_payment.twig.extension.class: Darvin\PaymentBundle\Twig\Extension\PaymentExtension

services:
    darvin_payment.twig.extension:
        class: '%darvin_payment.twig.extension.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_payment.url.builder'
        tags:
            - { name: twig.extension }
