parameters:
    darvin_payment.twig.extension.class: Darvin\PaymentBundle\Twig\Extension\PaymentExtension

services:
    darvin_payment.twig.extension:
        class: '%darvin_payment.twig.extension.class%'
        arguments:
            - '@darvin_payment.url.manager'
        tags:
            - { name: twig.extension }
