parameters:
    darvin_payment.url.payment_url_builder.class: 'Darvin\PaymentBundle\Url\PaymentUrlBuilder'
    darvin_payment.url.payment_url_manager.class: 'Darvin\PaymentBundle\Url\PaymentUrlManager'

services:
    Darvin\PaymentBundle\Url\PaymentUrlBuilderInterface: '@darvin_payment.url.payment_url_builder'

    darvin_payment.url.payment_url_builder:
        class: '%darvin_payment.url.payment_url_builder.class%'
        arguments:
            - '@router'
        public: true

    Darvin\PaymentBundle\Url\PaymentUrlManagerInterface: '@darvin_payment.url.payment_url_manager'

    darvin_payment.url.payment_url_manager:
        class: '%darvin_payment.url.payment_url_manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_payment.url.payment_url_builder'
            - '%darvin_payment.pre_auth%'
        public: true
