parameters:
    darvin_payment.url.builder.class: Darvin\PaymentBundle\Url\PaymentUrlBuilder

    darvin_payment.url.builder.twig.extension.class: Darvin\PaymentBundle\Twig\Extension\UrlBuilderExtension

services:
    Darvin\PaymentBundle\Url\PaymentUrlBuilderInterface: '@darvin_payment.url.builder'

    darvin_payment.url.builder:
        class: '%darvin_payment.url.builder.class%'
        arguments:
            - '@router'

    darvin_payment.url.builder.twig.extension:
        class: '%darvin_payment.url.builder.twig.extension.class%'
        arguments:
            - '@darvin_payment.url.builder'
            - '%darvin_payment.bridges%'
        tags:
            - { name: twig.extension }
