parameters:
    darvin_payment.url.builder.class: Darvin\PaymentBundle\Url\PaymentUrlBuilder

services:
    Darvin\PaymentBundle\Url\PaymentUrlBuilderInterface: '@darvin_payment.url.builder'

    darvin_payment.url.builder:
        class: '%darvin_payment.url.builder.class%'
        arguments:
            - '@router'
