parameters:
    darvin_payment.url.payment_url_builder.class: 'Darvin\PaymentBundle\Url\PaymentUrlBuilder'

services:
    Darvin\PaymentBundle\Url\PaymentUrlBuilderInterface: '@darvin_payment.url.payment_url_builder'

    darvin_payment.url.payment_url_builder:
        class: '%darvin_payment.url.payment_url_builder.class%'
        arguments:
            - '@router'
        public: true
