parameters:
    darvin_payment.url_builder.payment_url_builder.class: 'Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilder'

services:
    Darvin\PaymentBundle\UrlBuilder\PaymentUrlBuilderInterface: '@darvin_payment.url_builder.payment_url_builder'

    darvin_payment.url_builder.payment_url_builder:
        class: '%darvin_payment.url_builder.payment_url_builder.class%'
        arguments:
            - '@router'
        public: true
