menu:
    skip: true

order_by:
    createdAt: desc

route_blacklist:
    - new
    - edit

sortable_fields:
    createdAt: ~

view:
    index:
        fields:
            createdAt:
                type:   date
                widget: datetime
            level:
                size:   xs
                widget: log_level
            message:
                size:   free

    show:
        fields:
            createdAt:
                type:   date
                widget: datetime
            level:   ~
            message: ~

form:
    filter:
        fields:
            createdAtFrom: ~
            createdAtTo:   ~
