menu:
    position: 30

order_by:
    createdAt: desc

route_blacklist:
    - new

sortable_fields:
    createdAt: ~
    state:     ~

view:
    index:
        fields:
            id: ~
            createdAt:
                type:   date
                widget: datetime
            orderNumber: ~
            amount: ~
            currencyCode: ~
            clientId: ~
            clientEmail:
                size:   md
                type:   email
                widget: email_link
            description:
                size: sm
                widget:
                    text:
                        length: 24
                        rows: 1
                        trans: true
            state:
                size: sm
                widget:
                    payment_state:
                        property: state

            operation:
                size: md
                widget:
                    payment_operation: ~
            logs:
                type: link-with-add
                widget:
                    child_links:
                        child:      Darvin\PaymentBundle\Entity\Log
                        show_count: true
            transactionReference:
                size: free
            actionToken:
                size: free

form:
    filter:
        fields:
            createdAtFrom: ~
            createdAtTo:   ~
            orderNumber: ~
            clientEmail: ~
            state:
                type: Darvin\PaymentBundle\Form\Type\Admin\PaymentStateFilterType

    edit:
        fields:
            orderId: ~
            orderEntityClass: ~
            orderNumber: ~
            transactionReference: ~
            amount: ~
            currencyCode: ~
            clientId: ~
            clientEmail: ~
            description: ~
            state: ~
            actionToken: ~
