children:
    - Darvin\PaymentBundle\Entity\Event

menu:
    position: 30

order_by:
    createdAt: desc

route_blacklist:
    - new

sortable_fields:
    createdAt: ~
    state:     ~

view:
    index:
        fields:
            id: ~
            createdAt:
                type:   date
                widget: datetime
            order.number: ~
            client.email:
                size:   md
                type:   email
                widget: email_link
            amount: ~
            currency: ~
            description:
                size: sm
                widget:
                    text:
                        length: 24
                        rows: 1
                        trans: true
            state:
                size:   xs
                widget: payment_state

            operation:
                size: md
                widget:
                    payment_operation: ~
            events:
                type: link-with-add
                widget:
                    child_links:
                        child:      Darvin\PaymentBundle\Entity\Event
                        show_count: true

    show:
        fields:
            id: ~
            createdAt:
                type:   date
                widget: datetime
            order.number: ~
            amount: ~
            currency: ~
            order.id: ~
            order.entityClass: ~
            clientId: ~
            clientEmail:
                size:   md
                type:   email
                widget: email_link
            description:
                size: sm
                widget:
                    text:
                        length: 24
                        rows: 1
                        trans: true
            state:
                widget:
                    text:
                        property: state
            transactionReference:
                size: free
            token:
                size: free

form:
    filter:
        fields:
            createdAtFrom: ~
            createdAtTo:   ~
            state:
                type: Darvin\PaymentBundle\Form\Type\Admin\PaymentStateFilterType

    edit:
        fields:
            order.id: ~
            order.entityClass: ~
            order.number: ~
            transactionReference: ~
            amount: ~
            currency: ~
            client.id: ~
            client.class: ~
            client.email: ~
            description: ~
            state: ~
            token: ~
