menu:
    position: 30

route_blacklist:
    - new

sortable_fields:
    createdAt: ~
    state:     ~

view:
    index:
        fields:
            id: ~
            createdAt:
                type:   date
                widget: datetime
            orderId: ~
            amount: ~
            currencyCode: ~
            clientId: ~
            clientEmail:
                size:   md
                type:   email
                widget: email_link
            description:
                size: sm
                widget:
                    text:
                        length: 24
                        rows: 1
                        trans: true
            state:
                size: sm
                widget:
                    payment_state:
                        property: state

            operation:
                size: md
                widget:
                    payment_operation: ~
            transactionReference:
                size: free
            actionToken:
                size: free

form:
    filter:
        fields:
            createdAtFrom: ~
            createdAtTo:   ~
            orderId: ~
            clientEmail: ~
            state:
                type: Darvin\PaymentBundle\Form\Type\Admin\PaymentStateFilterType

    edit:
        fields:
            orderId: ~
            orderEntityClass: ~
            transactionReference: ~
            amount: ~
            currencyCode: ~
            clientId: ~
            clientEmail: ~
            description: ~
            state: ~
            actionToken: ~
