children:
    - Darvin\PaymentBundle\Entity\Event

menu:
    position: 30

order_by:
    createdAt: desc

route_blacklist:
    - new

sortable_fields:
    createdAt: ~
    state:     ~

view:
    index:
        fields:
            id: ~
            createdAt:
                type:   date
                widget: datetime
            order.number: ~
            client.email:
                size:   md
                type:   email
                widget: email_link
            amount: ~
            currency: ~
            description:
                size: sm
                widget:
                    text:
                        length: 24
                        rows: 1
                        trans: true
            state:
                size:   xs
                widget: payment_state

            operation:
                size: free
                widget:
                    payment_operation: ~
            events:
                type: link-with-add
                widget:
                    child_links:
                        child:      Darvin\PaymentBundle\Entity\Event
                        show_count: true

    show:
        fields:
            id: ~
            createdAt:
                type:   date
                widget: datetime
            amount: ~
            currency: ~
            description: ~
            transactionReference: ~
            token: ~

form:
    filter:
        fields:
            createdAtFrom: ~
            createdAtTo:   ~
            state:
                type: choice
                options:
                    choices: [ Darvin\PaymentBundle\DBAL\Type\PaymentStateType, getChoices ]

    edit:
        fields:
            amount: ~
            currency: ~
            description: ~
