menu:
    position: 30

route_blacklist:
    - new

view:
    index:
        fields:
            id: ~
            orderId: ~
            amount: ~
            currencyCode: ~
            clientId: ~
            clientEmail:
                size:   md
                type:   email
                widget: email_link
            description:
                size: sm
                widget:
                    text:
                        length: 24
                        rows: 1
                        trans: true
            state:
                size: sm
                widget:
                    payment_state:
                        property: state

            operation:
                size: md
                widget:
                    payment_capture:
                        property: state
            transactionReference:
                size: free
            actionToken:
                size: free

form:
    filter:
        fields:
            orderId: ~
    edit:
        fields:
            orderId: ~
            orderEntityClass: ~
            transactionReference: ~
            amount: ~
            currencyCode: ~
            clientId: ~
            clientEmail: ~
            description: ~
            state: ~
            actionToken: ~
