darvin_admin:
    sections:
        Darvin\PaymentBundle\Entity\Payment: '@DarvinPaymentBundle/Resources/config/admin/payment.yaml'
        Darvin\PaymentBundle\Entity\Event:
            alias:  payment_event
            config: '@DarvinPaymentBundle/Resources/config/admin/event.yaml'
