framework:
    workflows:
        payment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - Darvin\PaymentBundle\Entity\Payment
