framework:
    workflows:
        payment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - Darvin\PaymentBundle\Entity\Payment
            initial_marking: pending
            places:
                - approval
                - authorized
                - canceled
                - completed
                - expired
                - pending
                - refunded
            transitions:
                approve:
                    from: approval
                    to:   pending

                authorize:
                    from: pending
                    to:   authorized
                capture:
                    from: authorized
                    to:   completed
                void:
                    from: authorized
                    to:   canceled

                purchase:
                    from: pending
                    to:   completed
                cancel:
                    from: pending
                    to:   canceled

                expire:
                    from: pending
                    to:   expired

                refund:
                    from: completed
                    to:   refunded
