monolog:
    channels: ['payment']
    handlers:
        payment_logger:
            level:    debug #TODO подумать
            type:     stream
            path:     '%kernel.logs_dir%/payment.%kernel.environment%.log'
            channels: [payment]
