darvin_payment_payment_purchase:
    path: /{gatewayName}/purchase/{id}
    defaults: { _controller: DarvinPaymentBundle:Payment:purchase }
    requirements: { id: \d+ }

darvin_payment_payment_success_purchase:
    path: /{gatewayName}/complete-purchase/{token}
    defaults: { _controller: DarvinPaymentBundle:Payment:successPurchase }

darvin_payment_payment_failed_purchase:
    path: /{gatewayName}/failed-purchase/{token}
    defaults: { _controller: DarvinPaymentBundle:Payment:failedPurchase }

darvin_payment_payment_cancled_purchase:
    path: /{gatewayName}/canceled-purchase/{token}
    defaults: { _controller: DarvinPaymentBundle:Payment:cancelPurchase }