darvin_payment_payment_purchase:
    path: /{gatewayName}/purchase/{id}
    defaults: { _controller: DarvinPaymentBundle:Payment:purchase }
    requirements: { id: \d+ }

darvin_payment_payment_success:
    path: /{gatewayName}/complete/{token}
    defaults: { _controller: DarvinPaymentBundle:Payment:success }

darvin_payment_payment_failed:
    path: /{gatewayName}/failed/{token}
    defaults: { _controller: DarvinPaymentBundle:Payment:failed }

darvin_payment_payment_canceled:
    path: /{gatewayName}/canceled/{token}
    defaults: { _controller: DarvinPaymentBundle:Payment:canceled }
